### ISSUE TITLE
Request for some data

### ISSUE THREAD

**Issue by XvHaidong** [conallwang/MeGA#2]
Dear authors,
I greatly appreciate the work you've done!
I would like to follow your work, but I noticed that your dataset only includes ``306`` avatar. I understand that due to cloud storage limitations, you couldn't upload everything, but could you upload only the modified parts, like ``init_pts_150000.npy``, or provide the processing scripts instead? 
I believe most of readers already have the overlapping parts with the GaussianAvatars dataset. All we need are just the modified parts.
I would greatly appreciate it!

**Comment by conallwang** [comment]
Hi, Haidong

Thanks for your interests in our work. 

Yes, due to the limited cloud storage, we only release the data of Subject 306 this time. As you suggested, we'll upload our unique data (e.g., init_pts.npy, depths, face parsing results) as soon as possible.

Cong

**Comment by XvHaidong** [comment]
Thank you for the quick reply. I look forward to receiving your data and will be sure to cite your work!

**Comment by BobWalker-b** [comment]
@conallwang Dear team, 
I would also like to follow your work. I notice that your repository is updated frequently, and I wonder how long it might take until the next dataset release?
Best regards

**Comment by conallwang** [comment]
Because I'm working on another research project these days, I have few time to organize the data of MeGA.

**Comment by conallwang** [comment]
Hi, @BobWalker-b 

Because I'm working on another research project these days, I have few time to organize the data of MeGA. But I'll try my best to release the rest of data until next week. Thanks for your interests in our work!

Best regards,
Cong

**Comment by BobWalker-b** [comment]
Hi, @conallwang 
If it's possible, releasing data for just a few subjects would be wonderful! I'd greatly appreciate it.
Best regards,
Bob

**Comment by conallwang** [comment]
Hi, @BobWalker-b and @XvHaidong 

Sorry for the late responce. I have create a shared link ([https://drive.google.com/drive/folders/1xB6TgxwAxEl-lzjEuhr6cK6-2Meyf12Q?usp=sharing](https://drive.google.com/drive/folders/1xB6TgxwAxEl-lzjEuhr6cK6-2Meyf12Q?usp=sharing)) and upload our preprocessed data of Subject 218.
And I will update continuously the contents in this link once I get someone's data ready.

Best regards,
Cong

**Comment by BobWalker-b** [comment]
I have received this part of the data. Thank you very much for your prompt handling!
