### ISSUE TITLE
data preprocessing

### ISSUE THREAD

**Issue by xz0305** [conallwang/MeGA#3]
![00091_15_merge](https://github.com/user-attachments/assets/8f7fc2f0-e425-4c8f-b470-780cbc3d4774)

Hello, I would like to ask how you get the semantic map and depth map, is it BisenetV2?

**Comment by conallwang** [comment]
Hi, as mentioned in Sec. 6 of our paper

>  Based on their processed images, we further obtain facial parsing results for each image using an open-source
algorithm [17] and a depth map for each frame using Metashape software [25].

Actually, The semantic map (i.e., the facial parsing results) is obtained using MaskGAN based on [this repo](https://github.com/switchablenorms/CelebAMask-HQ), and the depth map is obtained based on the reconstruction algorithm of the Metashape software which you can download from [here](https://www.agisoft.com/downloads/installer/).

**Comment by xz0305** [comment]
This solved my problem, thank you very much
________________________________
发件人: conallwang ***@***.***>
发送时间: 2024年10月28日 11:26
收件人: conallwang/MeGA ***@***.***>
抄送: xz0305 ***@***.***>; Author ***@***.***>
主题: Re: [conallwang/MeGA] data preprocessing (Issue #3)


Hi, as mentioned in Sec. 6 of our paper

Based on their processed images, we further obtain facial parsing results for each image using an open-source
algorithm [17] and a depth map for each frame using Metashape software [25].

Actually, The semantic map (i.e., the facial parsing results) is obtained using MaskGAN based on this repo<https://github.com/switchablenorms/CelebAMask-HQ>, and the depth map is obtained based on the reconstruction algorithm of the Metashape software which you can download from here<https://www.agisoft.com/downloads/installer/>.

―
